language: python
python:
  - "2.7"

# command to install dependencies
install:
  - travis_wait 40 pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

# command to run tests
script:
  - python test_fsttrpgattributes.py
  - coverage run test_fsttrpgattributes.py

after_success:
  - coveralls