package:
  name: fsttrpgattributes
  version: 0.0.2

build:
 number: 1
 string: alpha

source:
  git_url: https://github.com/Krypticdator/SomeProject.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
about:
  summary: description